workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    scripts:
      - name: Gradle ile AAB Paketi Oluştur
        script: ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/bundle/release/*.aab
